# Generated by Django 2.1.7 on 2019-02-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_resto', models.CharField(max_length=255)),
                ('images', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_resto', models.CharField(max_length=255)),
                ('images', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('gaya', models.CharField(max_length=255)),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Home')),
            ],
        ),
    ]
